#!/bin/bash
SCRIPT_DIR="$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")")"

# shellcheck source=env
source "$SCRIPT_DIR/env"

# Check if required commands exist
declare -a REQ_CMDS=("Rscript" "pandoc")
for c in "${REQ_CMDS[@]}"; do
  "$SCRIPT_CHECKCMD" "$c" || exit
done

# Create target dir if not exist
if [ ! -d "$TARGET_DIR" ]; then
  mkdir "$TARGET_DIR" -p
fi

if [ ! -d "$TMP_DIR" ]; then
  mkdir "$TMP_DIR" -p
fi

if [ ! -d "$DIST_DIR" ]; then
  mkdir "$DIST_DIR" -p
fi

if [ ! -d "$CACHE_DIR" ]; then
  mkdir "$CACHE_DIR" -p
fi

# Copy src dir
cp -r "$SRC_DIR" "$TARGET_DIR/"

# Copy cache dir
cp -r "$CACHE_DIR" "$TMP_DIR/index_cache"

# Run R render script
cd "$TARGET_DIR" || exit
Rscript "$SCRIPT_RENDER"

cp -r "$TMP_DIR"/index_cache/* "$CACHE_DIR/"
